### ISSUE TITLE
USER STORY 1.1: Landing Page

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/wild-carbon#1]
# As a site user I can ascertain the sites purpose and view information regarding the services the company provides so that I decide whether or not I’d like to avail of the company’s services

## Tasks

- [x] Install Django, gunicorn, dj_database_url and psycopg2
- [x] Create superuser
- [x] Create wild carbon project and home app
- [x] Set up amazon s3 bucket
- [x] Set up elephant SQL
- [x] Deploy to Heroku
- [x] Code header and footer in base.html view and templates
- [x] Code landing page view , templates and URL
- [x] Configure messaging system
- [x] Configure a custom 404 page
- [x] Optimise content for search engines
- [x] Add favicon
- [x] Create privacy statement
- [x] Create sitemap.xml
- [x] Create robots.txt
- [x] Style the new front end features
- [x] Test the new functionality

## Acceptance Criteria

1	The user can ascertain the sites purpose and can view information regarding the services provided by the company
2	The following acceptance criteria for feature id '1' 'Landing Page' have been satisfied
2.1	The landing page has a navigation menu
2.2	The landing page is styled correctly for the site
2.3	The landing page contains an  image on load that fills the screen with the exception of space taken by the header
2.4	The image displayed on loading the landing page has an overlay stating the company name, 'Wild Carbon'
2.5	The landing page contains a section of text with the header  'What We Do' that explains what the company does
2.6	The landing page is responsive and resizes as necessary on a given screen
2.7	The landing page has a section of text with the header 'Coming Soon' that details a future venture of the company
2.8	A custom 404 page is displayed if a page is not found
3	The following acceptance criteria for feature id '25' 'Header' have been satisfied
3.1	The header has the company name displayed
3.2	Clicking the company name in the header will take the user to the Landing page
3.3	The header is at the top of the page
3.4	The header is styled correctly for the site
3.5	The header is responsive and resizes as necessary on a given screen
4	The following acceptance criteria for feature id '26' 'Footer' have been satisfied
4.1	The landing page has a footer that is at the bottom of the page and if the page is smaller than the view port 'sticks' to the bottom of the view port
4.2	The footer has the company name displayed
4.3	Clicking the company name in the footer will take the user to the Landing page
4.4	The footer contains a link to the privacy statement
4.5	The footer contains a copywrite notice
4.6	The footer contains an envelope icon that when clicked triggers the display of a modal with the header 'Contact Us' and displays the company email address
4.7	The contact us modal has a 'Done' button that closes the modal
4.8	The footer has a button that returns the page to the top on 'click'
4.9	The footer is responsive and resizes as necessary on a given screen
