### ISSUE TITLE
USER STORY 2.4: User Sign Out

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/wild-carbon#10]
# As a Site User / Staff Member (superuser permissions) / Site Admin (staff and superuser permissions) I can sign out of the website so that others cannot access my account from the device I’ve been using

## Tasks

- [ ] Configure allauth and Django for user / Admin sign out as necessary
- [ ] Style the new front end features
- [ ] Test the new functionality

## Acceptance Criteria

1	The Site User / Staff Member (superuser permissions) / Site Admin (staff and superuser permissions) can sign out of the website
2	The following acceptance criteria for feature id '2' 'Navigation' have been satisfied
2.1	On successful login, the navigation menu has a logout link in place of the login link that navigates to the sign out page
3	The following acceptance criteria for feature id '12' 'Sign Out' have been satisfied
3.1	On clicking sign out, the user is asked to confirm that they'd like to sign out
3.2	On successful sign out, the user is notified that they have successfully signed out
3.3	The sign out page is styled correctly for the site
3.4	The sign out page has the regular site header, footer and navigation with their regular associated links (as defined in the full header (id 25), navigation (id 2) and footer (id 26) feature acceptance criteria lists)
3.5	The sign out page is responsive and resizes for the screen on which it is being viewed
3.6	On successful logout the user is returned to the landing page
