### ISSUE TITLE
USER STORY 2.6: Plant Product Administration

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/wild-carbon#12]
# As Staff Member (superuser) / Site Admin (staff and superuser permissions) I can add, view, update and delete plant products so that I can administer the plants in the system

## Tasks

- [ ] Add plant app
- [ ] Add plant table to database model with fields as detailed in the entity relationship diagram
- [ ] Code the template, view and URL for the plant list page
- [ ] Code the template, view and URL for the plant update page
- [ ] Code the template, view and URL for the plant delete confirmation page
- [ ] Update the navigation menu to have a link to 'Plant Admin'
- [ ] Style the new front end features
- [ ] Test the new functionality

## Acceptance Criteria

1	A  (superuser) / Site Admin (staff and superuser permissions) can add, view, update and delete plant products
2	The following acceptance criteria for feature id '2' 'Navigation' have been satisfied
2.1	When logged in as a (superuser) / Site Admin (staff and superuser permissions) then navigation menu has a link to 'Plant Admin' that navigates to the 'Plant List' page
3	The following acceptance criteria for feature id '28' 'Add Plant' have been satisfied
3.1	The add plant page has the header 'Plant Product' just below the page header
3.2	Below the header is a label with the text 'Common Name'
3.3	Below the 'Common Name' label there is a validated common name input box that accepts up to 150 characters. The common name must be validated as a unique common name in the system
3.4	Below the 'Common Name' input box is a label with the text 'genus'
3.5	Below the label with the text genus is a validated genus input box that accepts up to 150 characters. The genus must be validated as a unique genus in the system
3.6	Below the genus input box there is a label with the text 'species'
3.7	Below the species label there is a validated species input box that accepts up to 150 characters
3.8	Below the species input box there is a label with the text 'description'
3.9	Below the description label there is a validated description text input box that allows characters to be entered
3.10	Below the description input box there is a label with the text 'image'
3.11	Below the image label there is a image select box that allows for a file to be selected for upload on form submission and linked to the plant being added
3.12	On selection of an image file, text stating the selected image is displayed
3.13	Below the image select box there is a label with the text 'sku'
3.14	Below the sku label there is an sku input box that is validated and allows for up to 150 characters to  be added. The sku must be validated as a unique sku in the system
3.15	Below the sku input box there is a label with the text 'price'
3.16	Below the price label there is a validated price input box that allows for a numerical input of up to 6 digits with 2 decimal places to be entered
3.17	Below the price input box there is a button with text 'add' that adds the plant to the database on click
3.18	The add plant page  has the regular site header, footer and navigation with their regular associated links (as defined in the full header (id 25), navigation (id 2) and footer (id 26) feature acceptance criteria lists)
3.19	The add plant page is styled correctly for the site
3.20	The add plant page is responsive and resizes for the screen on which it is being viewed
4	The following acceptance criteria for feature id '8' 'Plant List' have been satisfied
4.1	The plant list page has the header 'Plants' just below the page header
4.2	Below the page header is an 'Add Plant' button that navigates the user to the add plant page
4.3	Below the 'add plant' button is a search box that filters the plant list based on the input. The Common Name, Genus, Species and  description fields in the system are checked for matches with the search query 
4.4	Below the search query box there is a 'Sort By' box that enables the user to sort by  Price 'high to low' and 'low to high'  or name 'a to z' or 'z to a'
4.5	By default the plant instance list is sorted in Common Name alphabetical order
4.6	Below the sort by box is a grid of all of the plants stored in the system
4.7	Each plant instance has an image of the plant in question
4.8	Each plant instance listed gives the common name, genus and species of the plant
4.9	Each instance of a plant gives the price of the plant in Euro
4.10	Below the price of each instance of a plant there is an edit link that navigates to the update page for the plant
4.11	Below the price of each instance of a plant there is a delete link that navigates to a delete confirmation page for the plant
4.12	The plant list page has the regular site header, footer and navigation with their regular associated links (as defined in the full header (id 25), navigation (id 2) and footer (id 26) feature acceptance criteria lists)
4.13	The plant list page is styled correctly for the site
4.14	The plant list page is responsive and resizes for the screen on which it is being viewed
5	The following acceptance criteria for feature id '29' 'Edit Plant' have been satisfied
5.1	The update plant page has the header 'Plant Product' just below the page header
5.2	Below the header is a label with the text 'Common Name'
5.3	Below the 'Common Name' label there is a validated common name input box that displays the plants currently held common name data on page load and accepts up to 150 characters. The common name must be validated as a unique common name in the system
5.4	Below the 'Common Name' input box is a label with the text 'genus'
5.5	Below the label with the text genus there is a validated genus input box  that displays the plants currently held genus data on page load and  that accepts up to 150 characters . The genus must be validated as a unique genus in the system
5.6	Below the genus input box there is a label with the text 'species'
5.7	Below the species label there is a validated input box  that displays the plants currently held species data on page load and that accepts up to 150 characters
5.8	Below the species input box there is a label with the text 'description'
5.9	Below the description label there is a validated text input box that displays the plants currently held description data on page load and that allows characters to be entered
5.10	Below the description input box there is a label with the text 'image'
5.11	Below the image label there is a thumbnail of any image that currently exists in the system for the product
5.12	Below the image label there is a image select box that allows for a file to be selected for upload on form submission and linked to the plant being added
5.13	On selection of an image file, text stating the selected image is displayed
5.14	Below the image select box there is a label with the text 'sku'
5.15	Below the sku label there is a validated input box that displays the plants currently held sku data on page load and that allows for up to 150 characters to  be added. The sku must be validated as a unique sku in the system
5.16	Below the sku input box there is a label with the text 'price'
5.17	Below the price label there is an input box that displays the plants currently held price data on page load and that allows for a numerical input of up to 6 digits with 2 decimal places to be entered
5.18	Below the price input box there is a button with text 'update' that updates the plant instance in the system on click
5.19	The edit plant page  has the regular site header, footer and navigation with their regular associated links (as defined in the full header (id 25), navigation (id 2) and footer (id 26) feature acceptance criteria lists)
5.20	The edit plant page is styled correctly for the site
5.21	The edit plant page is responsive and resizes for the screen on which it is being viewed
6	The following acceptance criteria for feature id '30' 'Delete Plant' have been satisfied
6.1	The delete confirmation page has the heading 'Plant Delete' just below the header
6.2	The plant delete confirmation page has the text 'Are your sure you want to delete the <common name of plant> plant?'
6.3	The plant delete confirmation page has a 'back' button that returns the user to the plant list page
6.4	The plant delete confirmation page has a 'yes' button that actions the deletion of the plant
6.5	The plant delete confirmation page has the regular site header, footer and navigation with their regular associated links (as defined in the full header (id 25), navigation (id 2) and footer (id 26) feature acceptance criteria lists)
6.6	The plant delete confirmation page is styled correctly for the site
6.7	The plant delete confirmation page is responsive and resizes for the screen on which it is being viewed
