### ISSUE TITLE
USER STORY 2.7: Plant Product Availability

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/wild-carbon#13]
# As a Staff Member (superuser) / Site Admin (staff and superuser permissions) I can select the plant products that I want listed as products available for the location so that, at any given time, only appropriate plants for that location can be purchased and plants don’t need deleting to un-list them (so the data doesn’t need re-entering should they become suitable for listing again in the future)

## Tasks

- [x] Create location app
- [x] Add location table to database model with fields as detailed in the entity relationship diagram
- [x] Code the template, view and URL for the plant availability page
- [x] Update the navigation menu to have a link to 'Plant Availability'
- [x] Style the new front end features
- [x] Test the new functionality

## Acceptance Criteria

1	The Staff Member (superuser) / Site Admin (staff and superuser permissions) can select the plant products that they want displayed on the location page
2	The following acceptance criteria for feature id '2' 'Navigation' have been satisfied
2.1	When logged in as a (superuser) / Site Admin (staff and superuser permissions) then the navigation menu has a link to 'Plant Availability' that navigates to the 'Plant Availability' page
3	The following acceptance criteria for feature id '18' 'Plant Product Availability' have been satisfied
3.1	The page has a header just below the page header with the text 'Plant Availability'
3.2	Below the header there is a list of all of the plant instances in the system each with a checkbox next to them
3.3	A checked checkbox indicates a link between the checkboxes corresponding plant and the location. The checkboxes are checked if the plant was previously selected as available at the location
3.4	Clicking a checkbox toggles between checked and unchecked
3.5	Below the list of plant instances and checkboxes there is a button with the text 'update' that creates or deletes a link between the plant instance and the location as appropriate dependent on the checked state of the plant instances corresponding checkbox
3.6	The plant availability page has the regular site header, footer and navigation with their regular associated links (as defined in the full header (id 25), navigation (id 2) and footer (id 26) feature acceptance criteria lists)
3.7	The plant availability page is styled correctly for the site
3.8	The plant availability page is responsive and resizes for the screen on which it is being viewed
