### ISSUE TITLE
USER STORY 2.8: Plant Product View

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/wild-carbon#14]
# As a site user I can view a list of plants that can be grown and planted on my behalf at the location so that my carbon footprint can be offset over time

## Tasks

- [ ] Code the template, view and URL for the carbon capture page reusing the template code used to show the plant admin list page
- [ ] Update the navigation menu to contain a link to the carbon capture page
- [ ] Optimise the content for search engines
- [ ] Style the new front end features
- [ ] Test the new functionality

## Acceptance Criteria

1	The site user can view a list of plants that can be grown and planted on my behalf at the location 
2	The following acceptance criteria for feature id '2' 'Navigation' have been satisfied
2.1	When logged in as a site user the navigation menu has a link to 'Capture Carbon' that navigates to the Capture Carbon page
3	The following acceptance criteria for feature id '20' 'Plant Product Details' have been satisfied
3.1	The plant product detail page includes an image of the plant selected
3.2	The plant instance listed gives the common name, genus and species of the plant
3.3	The price of the plant in Euro is displayed
3.4	The product detail page includes a description of the plant
3.5	The Product detail page includes a button with the text 'Continue Shopping' that navigates to the capture carbon page
4	The following acceptance criteria for feature id '9' 'Location Plant Products' have been satisfied
4.1	The capture carbon page contains an  image on load that fills the screen with the exception of space taken by the header
4.2	The image displayed on loading the  capture carbon page has an overlay with the text ' capture carbon'
4.3	Below the image that is full screen on page load, there is a header 'Our Location'
4.4	Below the our location header is a section of text that briefly describes the planting location
4.5	Below the section of text describing the planting location, there is a heading 'Available Plants'
4.6	Below the Available Plants header is a search box that filters the plant list based on the input. The Common Name, Genus, Species and  description data in the system are checked for matches with the search query 
4.7	Below the search query box there is a 'Sort By' box that enables the user to sort by  Price 'high to low' and 'low to high'  or name 'a to z' or 'z to a'
4.8	By default the plant instance list is sorted in Common Name alphabetical order
4.9	Each plant instance has an image of the plant in question
4.10	Each plant instance listed gives the common name, genus and species of the plant
4.11	Each instance of a plant gives the price of the plant in Euro
4.12	On hover, the plant instance obtains a drop shadow to indicate that it is a clickable link
4.13	Clicking a plant instance navigates to the product detail page for the plant
4.14	The capture carbon page has the regular site header, footer and navigation with their regular associated links (as defined in the full header (id 25), navigation (id 2) and footer (id 26) feature acceptance criteria lists)
4.15	The capture carbon page is styled correctly for the site
4.16	The capture carbon page is responsive and resizes for the screen on which it is being viewed
