### ISSUE TITLE
USER STORY 2.9: Basket

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/wild-carbon#15]
# As a site user I can select a collection of trees so that I can purchase all the trees I want planted at the location on my behalf at the same time

## Tasks

- [x] Code the basket data structure and session store
- [x] Code the template, view and URL for the basket page
- [x] Update the header to contain a link to the basket page
- [x] Style the new front end features
- [x] Test the new functionality

## Acceptance Criteria

1	The site user can select a collection of trees for purchase
2	The following acceptance criteria for feature id '25' 'Header' have been satisfied
2.1	The header has a basket icon that navigates to the basket page on click
3	The following acceptance criteria for feature id '20' 'Plant Product Details' have been satisfied
3.1	The product detail page includes a validated and required quantity selector / input box that allows for the entry of a desired positive integer quantity of the product
3.2	The quantity selector / input box has a plus and minus button that increases or decreases the quantity respectively by one on each instance of a button click
3.3	The default quantity in the product detail page is 1
3.4	The product details page has a button with the text 'add to basket' that adds the selected product with the user selected quantity to the basket
4	The following acceptance criteria for feature id '10' 'Basket' have been satisfied
4.1	Below the page header there is a header with the text 'Basket'
4.2	Below  the basket header there is a label with the text 'Basket Total:' followed by the total value of the products in the basket in Euro
4.3	Below the basket total there is a label with the text 'VAT @ 23%:' followed by a value representing 23% of the basket total in Euro
4.4	Below the vat line there is a label 'Grand Total:' which is the sum of the basket total and the vat value in Euro
4.5	Below the grand total there is a label stating 'Your basket contents is below'
4.6	The basket page includes a list of all plant products selected by the user 
4.7	Each plant instance has an image of the plant in question
4.8	Each plant instance listed gives the common name, genus and species of the plant
4.9	Each instance of a plant gives the price of the plant in Euro
4.10	The basket page includes a validated quantity selector under each plant instance that allows for the entry of a positive integer quantity of the product
4.11	Each plant instance quantity selector has a plus and minus button that increases or decreases the quantity respectively by one on each instance of a button click
4.12	Each plant instance in the basket page has an update link that updates the quantity of the plant instance in the basket on click
4.13	On update of the product quantity the user is notified of the status, success or failure, of the update
4.14	Each plant instance in the basket page has a remove link that removes the plant instance from the basket
4.15	On removal of the plant instance from the basket, the  user is notified of the status, success or failure, of the removal
4.16	The basket page has a button with the text 'Continue Shopping' that navigates to the carbon capture page on click
4.17	The basket page has the regular site header, footer and navigation with their regular associated links (as defined in the full header (id 25), navigation (id 2) and footer (id 26) feature acceptance criteria lists)
4.18	The basket page is styled correctly for the site
4.19	The basket page is responsive and resizes for the screen on which it is being viewed
