### ISSUE TITLE
USER STORY 2.10: Checkout

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/wild-carbon#16]
# As a site user I can purchase the service of the trees in my basket being planted and maintained on my behalf so that I can work towards my life’s carbon footprint being offset

## Tasks

- [ ] Configure stripe account
- [ ] Create a checkout app
- [ ] Update the database model in checkout to include the order model and order line item model as specified in the entity relationship diagram
- [ ] Code the checkout template, view and URL
- [ ] Code the order confirmation template, view and URL
- [ ] Code for the order and its line items to be entered into the database on successful payment completion
- [ ] Code for a confirmation email to be sent to the user on successful completion of a payment
- [ ] Style the new front end features
- [ ] Test the new functionality
