### ISSUE TITLE
USER STORY 2.11: Profile

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/wild-carbon#17]
# As a site user I can save my profile so that I don’t have to re-enter my details the next time I order

## Tasks

- [ ] Create the profile app
- [ ] Update the profile app database model with the User Profile model as defined in the entity relationship diagram 
- [ ] Code the profile page template, view and URL
- [ ] Style the new front end features
- [ ] Test the new functionality

## Acceptance Criteria

1	The site user can save their profile information
2	The following acceptance criteria for feature id '2' 'Navigation' have been satisfied
2.1	The navigation account menu has a link to the profile page
3	The following acceptance criteria for feature id '11' 'Checkout' have been satisfied
3.1	Below the country selection box there is a label stating 'Save my delivery information for future orders' and a checkbox that, when checked, triggers the profile information to be stored or updated as appropriate on successful order completion
4	The following acceptance criteria for feature id '22' 'Profile' have been satisfied
4.1	The profile page has a header 'My Profile' below the page header
4.2	Below the my profile heading is a label with the text 'Phone Number'
4.3	Below the phone number label is a validated phone number input box that allows for the entry of a numerical phone number of up to 20 digits
4.4	Below the phone number input box there is a label with the text 'Address 1'
4.5	Below the address 1 label is a validated address 1 input box that allows for the entry of up to 90 characters
4.6	Below the address 1 input box is a label with the text 'Address 2'
4.7	Below the address 2 label is a validated address 2 input box that allows the entry of up to 90 characters
4.8	Below the address 2 input box is a label with the text 'Town or City'
4.9	Below the town or city label is a validated town or city input box that allows for entry of up to 50 characters
4.10	Below the town or city input box is a label with the text 'County'
4.11	Below the county label is a validated county input box that allows for the entry of up to 50 characters
4.12	Below the county input box is a label with the text 'Post Code'
4.13	Below the post code label is a validated post code input box that  allows the entry of up 20 characters
4.14	Below the post code input box is a label with the text 'Country'
4.15	Below the country label is a validated country select box that allows the selection of a country
4.16	Below the country input box there is a button with the text 'Update Information' that triggers the profile information for the user held in the system to be updated as required on click
4.17	The user is notified of a successful update
4.18	The user profile fields are prepopulated with any existing profile data previously saved as the result of an order with the please save my data checkbox, checked or through the 'My Profile' page
4.19	The user profile page has the regular site header, footer and navigation with their regular associated links (as defined in the full header (id 25), navigation (id 2) and footer (id 26) feature acceptance criteria lists)
4.20	The profile page is styled correctly for the site
4.21	The profile page is responsive and resizes for the screen on which it is being viewed
