### ISSUE TITLE
USER STORY 2.12: Order History

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/wild-carbon#18]
# As a site user I can see my order history so that I can remind myself of what I’ve commissioned

## Tasks

- [ ] Add the order history into the profile page template, view and URL
- [ ] Configure admin pages to show order history and order line items
- [ ] Style the new front end features
- [ ] Test the new functionality

## Acceptance Criteria

1	The user can view their order history
2	The following acceptance criteria for feature id '17' 'Order History' have been satisfied
2.1	The profile page contains a heading 'Order History'
2.2	Below the order history heading there is a table with 4 headings, 'Order Number', 'Date' (date order was placed), 'Items' (the order line items) and 'Total' (grand total for the order)each with their associated data below them for each order placed by the user. Each order begins on a new line.
2.3	The administration pages allow the view of all orders and their line items (such that they can be processed)
