### ISSUE TITLE
USER STORY 3.1: Carbon summary

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/wild-carbon#19]
# As a site user I can see details regarding how much carbon the trees I’ve commissioned to be grown and planted will sequester so that I can see at a glance how I’m doing with regards to offsetting my life’s carbon footprint

## Tasks

- [ ] Code the carbon summary page template, view and URL in the profile app
- [ ] Style the new front end features
- [ ] Test the new functionality

## Acceptance Criteria

1	The user can see details regarding how much carbon the trees they've commissioned to be grown and planted will sequester 
2	The following acceptance criteria for feature id '2' 'Navigation' have been satisfied
2.1	The navigation account menu contains a link to the 'Carbon Summary' page
3	The following acceptance criteria for feature id '24' 'Carbon Summary' have been satisfied
3.1	The carbon summary page contains a header 'Carbon Summary'
3.2	Below the Carbon summary header there is a section of text that details the total number of trees that the user has commissioned to be grown and planted
3.3	Below the text detailing the number of trees commissioned to be grown and planted, there is a section of text that details the approximate number of kg that these trees will sequester in a period of 100 years
3.4	Below the text detailing the number of kg of carbon the trees will sequester there is a section of text detailing the remaining number of trees required to offset the remainder of the users approximate life's carbon footprint
3.5	The carbon summary page has the regular site header, footer and navigation with their regular associated links (as defined in the full header (id 25), navigation (id 2) and footer (id 26) feature acceptance criteria lists)
3.6	The carbon summary page is styled correctly for the site
3.7	The carbon summary page is responsive and resizes for the screen on which it is being viewed
