### ISSUE TITLE
USER STORY 1.2: Navigation

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/wild-carbon#2]
# As a site user I can intuitively navigate the website so that I can find the information and site services I would like to access

## Tasks

- [x] Code the navigation menu into the base template
- [x] Style the navigation menu correctly for the site in the common CSS file
- [x] Test the new functionality

## Acceptance Criteria

1	The user can use the navigation menus to navigate the site and find the services and functions that they want to
2	The following acceptance criteria for feature id '25' 'Header' have been satisfied
2.1	The header contains the navigation links or the navigation 'burger icon' on small screens
3	The following acceptance criteria for feature id '2' 'Navigation' have been satisfied
3.1	The navigation menu has a  link to the home
3.2	The navigation menu is styled correctly for the site
3.3	The site is responsive and resizes as necessary on a given screen
