### ISSUE TITLE
USER STORY 3.2: Plant status

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/wild-carbon#20]
# As a Staff Member (superuser permissions) / Site Admin (staff and superuser permissions) I can see a list of all plant records with their current states and change their state so that I can take appropriate action  and move the plants through the planting workflow appropriately

## Tasks

- [ ] Add plant record model to the database with associated fields as defined in the entity relationship diagram
- [ ] Add the plant status model to the plant app along with all associated data as shown in the entity relationship diagram
- [ ] Code for a plant intent to written to the database for each tree commissioned in an order and set its initial state to pending
- [ ] Code the Planting Records page template, view and URL
- [ ] Style the new front end features
- [ ] Test the new functionality

## Acceptance Criteria

1	The Staff Member (superuser permissions) / Site Admin (staff and superuser permissions) can see a list of all plant records with their states and change their state
2	The following acceptance criteria for feature id '2' 'Navigation' have been satisfied
2.1	When logged in as a Staff Member (superuser permissions) / Site Admin (staff and superuser permissions) the navigation menu has a link to the Plant Records page
3	The following acceptance criteria for feature id '14' 'Plant Record View' have been satisfied
3.1	The plant record page has the heading 'Planting Records' just below the page header
3.2	The planting record page has a heading 'Tree Pending' below which there is a list of the plants (trees) that are in a state of pending. The table has labelled columns for 'name' (common name) and 'id' (plant id) and each new plant starts on a new row.
3.3	The planting record page has a heading 'Tree Growing' below which there is a list of the plants (trees) that are in a state of growing. The table has labelled columns for 'name' (common name) and 'id' (plant id) and each new plant starts on a new row.
3.4	The planting record page has a heading 'Tree Planted' below which there is a list of the plants (trees) that are in a state of growing. The table has labelled columns for 'name' (common name), 'id' (plant id) and date (date planted) and each new plant starts on a new row.
3.5	All plant records in the all lists on the planting record page have an edit link next to them if they are not in a state of planted which, when clicked, navigates to the plant status page for the plant the link is next to
3.6	The plant record page has the regular site header, footer and navigation with their regular associated links (as defined in the full header (id 25), navigation (id 2) and footer (id 26) feature acceptance criteria lists)
3.7	Th plant record page is styled correctly for the site
3.8	The plant record page is responsive and resizes for the screen on which it is being viewed
4	The following acceptance criteria for feature id '15' 'Plant Record Status' have been satisfied
4.1	A plant record with an initial workflow state of pending is created in the system for each plant commission purchased in users orders
4.2	The plant status page has the heading 'Plant Status' below the page header
4.3	The plant status page has a heading that is the common name of the tree who status is being altered
4.4	Below the trees common name header is the plant id of the plant who's status is being altered
4.5	Below the plant id is a select box that shows the current state of the plant and on click shows the state options 'pending' and 'growing' if the current state is 'pending' or 'growing' and 'planted' if the current state is 'growing'
4.6	The plant status page has the regular site header, footer and navigation with their regular associated links (as defined in the full header (id 25), navigation (id 2) and footer (id 26) feature acceptance criteria lists)
4.7	The plant status page is styled correctly for the site
4.8	The plant status page is responsive and resizes for the screen on which it is being viewed
