### ISSUE TITLE
USER STORY 3.3: Plant record admin

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/wild-carbon#21]
# As a Staff Member (superuser permissions) / Site Admin (staff and superuser permissions) I can add and delete plant records for the rewilding site so that I can add and delete location plant records not linked to an order

## Tasks

- [ ] Update the plant record view template
- [ ] Code the add plant record template, view and URL
- [ ] Code the delete plant record template, view and URL
- [ ] Style the new front end features
- [ ] Test the new functionality

## Acceptance Criteria

1	The Staff Member (superuser permissions) / Site Admin (staff and superuser permissions) can add and delete plant records for the rewilding site
2	The following acceptance criteria for feature id '14' 'Plant Record View' have been satisfied
2.1	Below the planting record page Planting record header there is a button with the text 'Add Record' that navigates to the add plant record page on click
2.2	All plant records in all lists on the planting record page that are not linked to a customer order have a delete link next to them, if they are not in a state of planted, which navigates to the plant record delete confirmation page for the plant in question
3	The following acceptance criteria for feature id '16' 'Plant Record Add' have been satisfied
3.1	The add plant record page has a heading 'Plant Record' just below the header
3.2	Below the plant record header there is a label with the text 'plant'
3.3	Below the plant label there is a plant select box that enables the Staff Member (superuser permissions) / Site Admin (staff and superuser permissions) to select one of the plants stored in the plant table of the database
3.4	Below the plant select box there is a label with the text 'State'
3.5	Below the state label there is a select box that allows the Staff Member (superuser permissions) / Site Admin (staff and superuser permissions) to select from 'pending' 'growing' or 'planted'
3.6	Below the state select box there is a button with the text 'Add' that triggers the creation of a new plant record with the data from the plant and state form fields
3.7	The add plant record page has the regular site header, footer and navigation with their regular associated links (as defined in the full header (id 25), navigation (id 2) and footer (id 26) feature acceptance criteria lists)
3.8	The add plant record page is styled correctly for the site
3.9	The add plant record page is responsive and resizes for the screen on which it is being viewed
4	The following acceptance criteria for feature id '31' 'Plant Record Delete' have been satisfied
4.1	The plant record delete confirmation page has the heading 'Plant Record Delete' just below the header
4.2	The plant record delete confirmation page has the text 'Are your sure you want to delete the <common name of plant> <id of plant> plant record?'
4.3	The plant record delete confirmation page has a 'back' button that returns to user to the plant record view page
4.4	The plant record delete confirmation page has a 'yes' button that actions the deletion of the plant
4.5	The plant record delete confirmation page has the regular site header, footer and navigation with their regular associated links (as defined in the full header (id 25), navigation (id 2) and footer (id 26) feature acceptance criteria lists)
4.6	The plant record delete confirmation page is styled correctly for the site
4.7	The plant record delete confirmation page is responsive and resizes for the screen on which it is being viewed
