### ISSUE TITLE
USER STORY 3.4: User order plant status

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/wild-carbon#22]
# As a site user I can see the status of trees linked to my orders so that I can see when orders have been completely fulfilled

## Tasks

- [x] Update profile page template and view as necessary
- [x] Style the new front end features
- [x] Test the new functionality

## Acceptance Criteria

1	The site user can see the status of trees linked to their orders
2	The following acceptance criteria for feature id '17' 'Order History' have been satisfied
2.1	Below each order entry there is a heading 'Associated Plant Records' followed by a table with 4 headings, 'Name' (common name), 'Id' (unique plant id), 'State' (pending/growing/planted) and 'Date' (date when into current state) each with their associated data below them for each order placed by the user. Each plant begins on a new line
