### ISSUE TITLE
USER STORY 3.5: User plant records

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/wild-carbon#23]
# As a site user I can view list of all the trees that I’ve commissioned and the trees planting workflow state so that I can see at a glance a summary of the trees I’ve commissioned and what workflow state they’re currently in without having to look at order details at the same time 

## Tasks

- [x] Update the carbon summary page template and view
- [x] Style the new front end features
- [x] Test the new functionality

## Acceptance Criteria

1	The site user can view list of all the trees that they've commissioned and the trees planting workflow state
2	The following acceptance criteria for feature id '23' 'Plant Summary' have been satisfied
2.1	The carbon summary page contains a header 'Your Planting Records' above tables containing the trees commissioned by the user
2.2	The  carbon summary page has a heading 'Planted Trees' below which there is a list of the plants (trees) that are in a state of planted. The table has labelled columns for  'name' (common name), 'id' (plant id) and date (date planted) and each new plant starts on a new row
2.3	The  carbon summary page has a heading 'Growing Trees' below which there is a list of the plants (trees) that are in a state of growing. The table has labelled columns for 'name' (common name) and 'id' (plant id)  and date (date went to growing state) and each new plant starts on a new row
2.4	The carbon summary page has a heading 'Pending Trees' below which there is a list of the plants (trees) that are in a state of pending. The table has labelled columns for 'name' (common name) and 'id' (plant id) and date (date date went into pending state) and each new plant starts on a new row
