### ISSUE TITLE
USER STORY 1.3: About us

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/wild-carbon#3]
# As a site user I can read about the company ethos so that I can find out if the company is one from whom I would like to make purchases

## Tasks

- [] Code About Us page view, templates and URL
- [] Add a link to the about us page in the navigation menu
- [] Add the image link to the landing page
- [] Optimise content for search engines
- [] Style the new front end features
- [] Test the new functionality

## Acceptance Criteria

1	The user can read about the company ethos
2	The following acceptance criteria for feature id '2' 'Navigation' have been satisfied
2.1	The navigation menu has a link to the 'Abou Us' page
3	The following acceptance criteria for feature id '1' 'Landing Page' have been satisfied
3.1	The landing page has a link that is an image that navigates to the about us page
3.2	On hover the image link obtains a drop shadow to indicated it is a clickable link
4	The following acceptance criteria for feature id '4' 'About Us' have been satisfied
4.1	The about us page contains an  image on load that fills the screen with the exception of space taken by the header
4.2	The image displayed on loading the about us page has an overlay with the text 'About Us'
4.3	The about us page has a section of text with the header 'Who we are' that describes the company ethos
4.4	The about us page has the regular site header, footer and navigation with their regular associated links (as defined in the full header (id 25), navigation (id 2) and footer (id 26) feature acceptance criteria lists)
4.5	The about us page is styled correctly for the site
4.6	The about us page is responsive and resizes as necessary on a given screen
