### ISSUE TITLE
USER STORY 1.4: Newsletter

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/wild-carbon#4]
# As a site user I can sign up for a newsletter so that I can be informed of any news, events or other information related to the company

## Tasks

- [x] Set up mailchimp account
- [x] Integrate a mailchimp JavaScript form into the landing page template
- [x] Style the new front end features
- [x] Test the new features

## Acceptance Criteria

1	The user can sign up to receive wild carbon company newsletters
2	The following acceptance criteria for feature id '1' 'Landing Page' have been satisfied
2.1	The landing page has a heading 'Newsletter' followed by a section of text detailing the type of content contained in the newsletters
2.2	The landing page has an email input box below the newsletter heading and introductory text
2.3	The email input box is validated and is required
3	The following acceptance criteria for feature id '3' 'Newsletter' have been satisfied
3.1	There is a submit button below the newsletter input boxes that submits the form data resulting in the addition of the users name and email address to the newsletter mailing list
