### ISSUE TITLE
USER STORY 1.5: Facebook

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/wild-carbon#5]
# As a site user I can navigate to the company Facebook business page so that I can see information relating to the company’s activities that have been posted on Facebook and are not present on the company website

## Tasks

- [x] Set up a company Facebook account
- [x] Configure the company Facebook page
- [x] Add Facebook icon link to the footer in base.html
- [x] Style the new front end features
- [x] Test the new functionality

## Acceptance Criteria

1	The user can navigate to the company Facebook page from the website
2	The following acceptance criteria for feature id '26' 'Footer' have been satisfied
2.1	The footer has a Facebook icon link
3	The following acceptance criteria for feature id '5' 'Facebook' have been satisfied
3.1	On click of the Facebook link icon, a new tab is opened and the company Facebook page is loaded in the new tab
