### ISSUE TITLE
USER STORY 1.6: How it Works

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/wild-carbon#6]
# As a site user I can view more in depth information about the services provided by wild carbon than can be found on the landing page so that I can feel confident I’m investing in the right company to offset my carbon

## Tasks

- [x] Code the How it Works page template, view and URL
- [x] Add a link to the how it works page in the navigation menu
- [x] Add the image link to the landing page
- [x] Style the new front end features correctly for the site
- [x] Test the new features

## Acceptance Criteria

1	The user can view more in depth information about the company than can be found on the landing page
2	The following acceptance criteria for feature id '2' 'Navigation' have been satisfied
2.1	The navigation menu contains a link to the 'How it Works' page
2.2	The navigation link is styled correctly for the site
3	The following acceptance criteria for feature id '1' 'Landing Page' have been satisfied
3.1	The landing page has a link that is an image that navigates to the 'how it works' page
3.2	On hover the how it works image link obtains a drop shadow to indicated it is a clickable link
4	The following acceptance criteria for feature id '19' 'How it Works' have been satisfied
4.1	The how it works page contains an  image on load that fills the screen with the exception of space taken by the header
4.2	The image displayed on loading the how it works page has an overlay with the text 'how it works'
4.3	The how it works page has a section of text with the header 'More about our service' that describes the companies service in more detail than can be found on the landing page
4.4	The how it works page has a section of text with the header 'Wild Facts' that details some facts relevant to the service
4.5	The How it Works page has a useful link section with links to external sites with relevant information. Clicking a link opens the external page in a new tab.
4.6	The how it works page has the regular site header, footer and navigation with their regular associated links (as defined in the full header (id 25), navigation (id 2) and footer (id 26) feature acceptance criteria lists)
4.7	The how it works page is styled correctly for the site
4.8	The how it works page is responsive and resizes as necessary on a given screen
