### ISSUE TITLE
USER STORY 2.1: User registration

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/wild-carbon#7]
# As a Site User I can register on the website and create an account so that I can log into the website and make purchases

## Tasks

- [ ] Install allauth
- [ ] Configure allauth and Django for user registration
- [ ] Code the registration page template, view and URL
- [ ] Add a link to the registration page in the navigation account menu
- [ ] Configure for sending email verification emails
- [ ] Style the new front end features
- [ ] Test the new functionality

## Acceptance Criteria

1	The user can register an account on the website
2	The following acceptance criteria for feature id '25' 'Header' have been satisfied
2.1	The header has an icon that when clicked opens the navigation account menu
3	The following acceptance criteria for feature id '2' 'Navigation' have been satisfied
3.1	The navigation account menu has a link to the user 'Registration' Page that navigates to the Registration page
3.2	On successful Admin (staff permissions) login, the navigation menu has an admin page link that navigates to the admin page
4	The following acceptance criteria for feature id '6' 'Register'  have been satisfied
4.1	The user registration page has a 'Username' field that is validated and is a required field
4.2	The user registration page has an 'Email' field that is required
4.3	The user registration page 'Email' field is validated and an invalid email address cannot be submitted
4.4	The user registration page has a 'Password' and password confirmation field that are validated and that must match for submission to take place
4.5	The user registration page has a 'Sign Up'  button
4.6	On successful registration there is a message to the user requesting that they check for an email verification email
4.7	On clicking or navigating to the link in the email verification email, the user's email address is verified and the user account is activated
4.8	The user registration page is styled correctly for the site
4.9	The registration page has the regular site header, footer and navigation with their regular associated links (as defined in the full header (id 25), navigation (id 2) and footer (id 26) feature acceptance criteria lists)
4.10	The user registration page is responsive and resizes as necessary on a given screen
