### ISSUE TITLE
USER STORY 2.2: User Sign In

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/wild-carbon#8]
# As a Site User / Staff Member (superuser permissions) / Site Admin (staff and superuser permissions) I can sign into the website so that I can make purchases

## Tasks

- [x] Copy allauth templates for customisation and customise
- [x] Configure allauth and Django for user / Admin sign in as necessary
- [x] Style the new front end features
- [x] Test the new functionality

## Acceptance Criteria

1	The site user / admin can sign into the website with their previously registered credentials
2	The following acceptance criteria for feature id '2' 'Navigation' have been satisfied
2.1	The navigation account menu has navigation link to the user 'login' Page that navigates to the sign in page
3	The following acceptance criteria for feature id '7' 'Sign In' have been satisfied
3.1	The 'Login' page has a link to the user registration page (for use in the event a user has not yet registered)
3.2	The 'Login' page has a username field that is validates and is a required field
3.3	The 'Login' page has a password field that is validated and is a required field
3.4	On successful sign in the user is notified that they have successfully signed in
3.5	The login page is styled correctly for the site
3.6	The sign in page has the regular site header, footer and navigation with their regular associated links (as defined in the full header (id 25), navigation (id 2) and footer (id 26) feature acceptance criteria lists)
3.7	The login page is responsive and resizes for the screen on which it is being viewed
