### ISSUE TITLE
USER STORY 2.3: Password Recovery

### ISSUE THREAD

**Issue by Stephen-J-Whitaker** [Stephen-J-Whitaker/wild-carbon#9]
# As a site user I can easily recover my password in case I forget it so that I can regain access to my account

## Tasks

- [ ] Customise allauth password recovery templates
- [ ] Style the new front end features
- [ ] Test the new functionality

## Acceptance Criteria

1	The site user can regain access to their account in the event they lose their password
2	The following acceptance criteria for feature id '7' 'Sign In' have been satisfied
2.1	The 'sign in' page has a link to the password recovery page
3	The following acceptance criteria for feature id '32' 'Password Reset' have been satisfied
3.1	The password reset page has a header with the text 'Password Reset'
3.2	The password reset page has a validated and required email input box
3.3	The password reset page has a button with the text 'Reset Password' that submits the email address and triggers the sending of a password reset email should the entered email be valid
3.4	On successful submission of the email address, an email is sent to the user and the 'password reset link email sent notification' page is loaded
3.5	The user is notified on submission of an email address that is not linked  to a registered user
3.6	The password reset page has a button with the text back that navigates to the sign in page on click
3.7	The password reset page is styled correctly for the site
3.8	The  password reset page has the regular site header, footer and navigation with their regular associated links (as defined in the full header (id 25), navigation (id 2) and footer (id 26) feature acceptance criteria lists)
3.9	The  password reset page is responsive and resizes for the screen on which it is being viewed
3.10	The password reset link email sent notification page contains the header 'Password Reset' and text notifying the user that the email with the reset link in it has been sent to them
3.11	The password reset link email sent notification page is styled correctly for the site
3.12	The password reset link email sent notification page has the regular site header, footer and navigation with their regular associated links (as defined in the full header (id 25), navigation (id 2) and footer (id 26) feature acceptance criteria lists)
3.13	The password reset link email sent notification page is responsive and resizes for the screen on which it is being viewed
3.14	The password reset link email sent notification page has a button with the text home that navigates to the landing page on click
3.15	The password reset email has a link that navigates to the new password page on click
3.16	The new password page contains the header 'Change Password'
3.17	The new password page contains a 'New Password' label and a validated and required new password input box
3.18	The new password page contains a 'New Password (again)' label and a validated and required new password (again) input box
3.19	The new password page contains a button with the text 'Change Password' that actions the change of password and loads a page with the text 'Your password is now changed' on successful password change
3.20	The new password page contains a button with the text 'Sign In' that navigates to the sign in page on click
3.21	The new password page is styled correctly for the site
3.22	The new password page has the regular site header, footer and navigation with their regular associated links (as defined in the full header (id 25), navigation (id 2) and footer (id 26) feature acceptance criteria lists)
3.23	The  new password page is responsive and resizes for the screen on which it is being viewed
